"""
Public Flow YAML validation and generation facade.

FYI: Functionalities created, edited and used in this file should be documented
in SE Design: "https://<domain>/wiki/spaces/AS/pages/6066602590"
[DISCLAIMER]

FYI: It is essential that the code generated by this module and the yaml it
receives do not contain characters ">" or "~" as base64 encoder and decoder are
not schematic between OS implementations on how to encode them!

There are tests asserting that.
"""

import yaml

from mstrio.python_execution.script import ReadOnlyCode as _ReadOnlyCode

from .flow_emitter import emit_flow_code as _emit_flow_code
from .flow_graph import compile_flow_graph as _compile_flow_graph
from .flow_nodes.base import AnyEntry as _AnyEntry
from .flow_nodes.base import InvalidInput as _InvalidInput
from .flow_validation import (
    validate_input_yaml_structure as _validate_input_yaml_structure,
)


def _parse_input_yaml(input_yaml_string: str) -> _AnyEntry:
    if not isinstance(input_yaml_string, str):
        raise _InvalidInput("Input YAML should be provided as a string.")

    try:
        return yaml.load(input_yaml_string.strip(), yaml.SafeLoader)
    except yaml.YAMLError as error:
        detail = getattr(error, "problem", None) or "unable to parse the document"
        raise _InvalidInput(f"Input YAML is invalid: {detail}.") from error
    except RecursionError as error:
        raise _InvalidInput("Input YAML is nested too deeply.") from error


def generate_flow_content(input_yaml_string: str) -> str:
    """Generate Flow Script code from YAML produced by the Flows plugin."""
    parsed_yaml = _parse_input_yaml(input_yaml_string)
    _validate_input_yaml_structure(parsed_yaml)
    graph = _compile_flow_graph(parsed_yaml["steps"])

    code = _emit_flow_code(graph, parsed_yaml["connection"])
    if not _ReadOnlyCode(code).is_valid():
        raise SyntaxError(
            f"[INTERNAL ERROR]: Generator creates invalid code!\n\n{code}"
        )
    return code
