language: python

cache: pip

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
    fast_finish: true
    allow_failures:
    - python: 3.8-dev

install:
    - pip install -e .

script:
    - pytest tests
