[build-system]
requires = ["hatchling >= 1.14.0", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "mstrio/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/code_snippets",
    "/script-templates",
    "/mstrio",
    "/workflows",
    "/NEWS.md",
    "/README.md",
    "/USAGE.md",
    "/requirements.txt",
    "/setup.cfg",
]

[tool.hatch.build.targets.wheel]
packages = ["mstrio"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[project]
name = "mstrio-py"
description = "Python interface for the MicroStrategy REST API"
authors = [
    { name = "MicroStrategy", email = "bkaczynski@microstrategy.com" }
]
requires-python = ">=3.10"
license = {text = "Apache License 2.0"}
readme = "README.md"
dynamic = ["version", "dependencies"]

[project.urls]
"Bug Tracker" = "https://github.com/MicroStrategy/mstrio-py/issues"
"Documentation" = "https://www2.microstrategy.com/producthelp/Current/mstrio-py/"
"Source Code" = "https://github.com/MicroStrategy/mstrio-py"
"Quick Manual" = "https://www2.microstrategy.com/producthelp/current/FederatedAnalytics/en-us/Content/mstr_for_jupyter.htm"
