
Vagrant::Project.configure(:workspace) do |env|
  windows_workspace :windows_workspace do

    provider{
      network{
        ip_address "10.4.83.4"
      }
      
      ecosystem_cookbooks_path = File.expand_path("microstrategy/ecosystem-cookbooks", $WORKSPACE_SETTINGS[:paths][:projects][:root])

      short_ecosystem_cookbooks_path = Pathname.new(ecosystem_cookbooks_path).relative_path_from(Pathname.new(ENV['HOME']))

      synced_folders{
        host_path ecosystem_cookbooks_path
        guest_path "/Users/vagrant#{short_ecosystem_cookbooks_path}"
        create true
      }
    }

  end
end
