
Vagrant::Project.configure(:workspace) do |env|
  linux_workspace :linux_workspace do

  	provider {

      sync_vagrant_folder false
      
      network{
        ip_address "10.4.83.2"
      }

      short_project_paths_home = $WORKSPACE_SETTINGS[:paths][:project][:home][/#{ENV['HOME']}(.*)/, 1]
      synced_folders{
        host_path  $WORKSPACE_SETTINGS[:paths][:project][:home]
        guest_path "/home/vagrant#{short_project_paths_home}"
        create true
      }
      
      ecosystem_cookbooks_path = File.expand_path("microstrategy/ecosystem-cookbooks", $WORKSPACE_SETTINGS[:paths][:projects][:root])
      short_ecosystem_cookbooks_path = ecosystem_cookbooks_path[/#{ENV['HOME']}(.*)/, 1]
      synced_folders{
        host_path ecosystem_cookbooks_path
        guest_path "/home/vagrant#{short_ecosystem_cookbooks_path}"
        create true
      }

      ecosystem_root_path = File.expand_path("microstrategy/ecosystem-incubator/eco.root", $WORKSPACE_SETTINGS[:paths][:projects][:root])
      synced_folders{
        host_path ecosystem_root_path
        guest_path $WORKSPACE_SETTINGS[:ecosystem][:root][:paths][:home]
        create true
      }

    }
  end
end
