from requests import Response

from mstrio.connection import Connection
from mstrio.utils.api_helpers import add_comment_to_dict
from mstrio.utils.error_handlers import ErrorHandler

# region privileges


@ErrorHandler(err_msg="Error getting privileges.")
def get_privileges(connection: Connection, error_msg=None):
    """Get the set of available privileges for the platform.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/privileges',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error getting privilege categories.")
def get_privilege_categories(connection: Connection, error_msg=None):
    """Get the set of available privilege categories for the platform.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/privileges/categories',
        headers={'X-MSTR-ProjectID': None},
    )


# endregion

# region ldap


@ErrorHandler(err_msg="Error getting LDAP information.")
def get_ldap_info(connection: Connection, error_msg=None):
    """Get the existing LDAP configuration and attributes which are stored in
    the Intelligence Server metadata. You may update and save it back later
    based on the existing configuration.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/ldap/configuration',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error creating LDAP configuration.")
def create_ldap_config(connection: Connection, body, error_msg=None):
    """Create a new LDAP configuration and save it to the Intelligence Server.
    There is only one LDAP configuration in Intelligence Server metadata, so
    this operation will replace the old configuration if exists. The request
    body should include all configuration fields.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/iserver/ldap/configuration',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error deleting LDAP configuration.")
def delete_ldap_config(connection: Connection, error_msg=None):
    """Delete the existing LDAP configuration from Intelligence Server
    metadata.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.delete(
        endpoint='/api/iserver/ldap/configuration',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error updating LDAP configuration.")
def update_ldap_config(connection: Connection, body, error_msg=None):
    """Update the existing LDAP configuration and save it to the Intelligence
    Server. There is only one LDAP configuration in Intelligence Server
    metadata, so this operation will replace the old configuration. The request
    body should only contain fields that will be updated.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.patch(
        endpoint='/api/iserver/ldap/configuration',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error getting LDAP attributes.")
def get_ldap_attributes(connection: Connection, error_msg=None):
    """Get LDAP attributes list. You may want to import more attributes for
    users. The API will provides you the list of available LDAP attributes,
    from which you may choose some extra attributes to import.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/ldap/attributes',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error getting LDAP certificate information.")
def get_ldap_certificate_info(connection: Connection, error_msg=None):
    """Get LDAP server certificate info. The communication between the
    Intelligence Server and LDAP server can be encrypted by SSL (optional).
    This API will return basic information about the LDAP server certificate.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/ldap/certificate',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error updating LDAP certificate.")
def upload_ldap_certificate(connection: Connection, body, error_msg=None):
    """Upload LDAP server certificate for encrypted communication. The
    communication between the Intelligence Server and the LDAP server can be
    encrypted by SSL (optional). The certificate uploaded in this API will be
    added to the trust store of the Intelligence Server, and later used for the
    SSL communication between the Intelligence Server and the LDAP server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/iserver/ldap/certificate',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error verifying LDAP binding.")
def verify_ldap_binding(connection: Connection, error_msg=None):
    """Verify the LDAP username and password binding.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/ldap/authuserbinds',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error getting LDAP batch import status.")
def get_ldap_batch_import_status(connection: Connection, error_msg=None):
    """Get LDAP batch import status. You can get the progress of LDAP batch
    import, including its status (e.g. failed, stopped, undergoing, and
    canceled). If there is LDAP batch import undergoing, you can also get the
    number of users and groups which have already been imported.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/ldap/import',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error stopping LDAP batch import.")
def stop_ldap_batch_import(connection: Connection, error_msg=None):
    """Stop the LDAP batch import if it exists. This operation will be ignored
    if there is no undergoing LDAP batch import.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/iserver/ldap/import',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error doing LDAP batch import.")
def do_ldap_batch_import(connection: Connection, error_msg=None):
    """Do LDAP batch import now. This API starts the LDAP batch import, which
    will import both groups and users from the LDAP server. No request body is
    needed.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/iserver/ldap/import',
        headers={'X-MSTR-ProjectID': None},
    )


# endregion

# region rest settings


@ErrorHandler(err_msg="Error updating authentication configurations.")
def update_authentication_configs(connection: Connection, body, error_msg=None):
    """Update the authentication configuration settings for the current REST
    server. In the body parameter of the request, you specify the default
    authentication mode and the authentication modes that will be available to
    connect to an Intelligence Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling


    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/auth',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error updating collaboration server configurations.")
def update_collaboration_server_configs(connection: Connection, body, error_msg=None):
    """Update the Collaboration Server configuration settings. In the body
    parameter of the request, you specify the base URL for the Collaboration
    Server, whether the collaboration service is enabled, and whether TLS
    (Transport Layer Security) secure communication is enabled. Enabling TLS
    requires configuring trust store settings on the REST Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/collaboration',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error updating web configurations.")
def update_web_configs(connection: Connection, body, error_msg=None):
    """Update the Strategy One Web configuration settings. In the body
    parameter of the request, you specify the base URL for the Strategy One
    Web Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/microStrategyWeb',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error testing collaboration server connection.")
def test_collaboration_connection(connection: Connection, body, error_msg=None):
    """Test the connection between the REST Server and the Collaboration
    Server. In the body parameter of the request, you specify the base URL for
    the Collaboration Server and whether TLS (Transport Layer Security) secure
    communication is enabled. Enabling TLS requires configuring trust store
    settings on the REST Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/admin/restServerSettings/collaboration/connectionTest',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error updating intelligence server configurations.")
def update_iserver_configs(connection: Connection, body, error_msg=None):
    """Update the Intelligence Server configuration settings. In the body
    parameter of the request, you specify the default port and hostname, the
    initial and max connection pool size, the request timeout, the number of
    reports/documents and searches that can be kept in memory, whether a trust
    relationship has been set with the Intelligence Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/iServer',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error getting rest configurations.")
def get_rest_configs(connection: Connection, error_msg=None):
    """Get configuration settings for the current REST Server, including
    settings for authentication, the Collaboration Server, Google Analytics,
    and the Intelligence Server.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/admin/restServerSettings',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(
    err_msg="Error checking intelligence server - web server trust relationship."
)
def check_iserver_web_trust(connection: Connection, error_msg=None):
    """Check to see if there is a trust relationship between the Web Server and
    the Intelligence Server.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/admin/restServerSettings/iServer/trustRelationship',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(
    err_msg="Error setting intelligence server - web server trust relationship."
)
def set_iserver_web_trust(connection: Connection, body, error_msg=None):
    """Set up a trust relationship between the Web Server and the Intelligence
    Server. You obtain the authorization token needed to execute the request
    using POST /auth/login; you pass the authorization token in the request
    header. In the body parameter of the request, you specify the URL or other
    unique identifier for the Web Server.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/admin/restServerSettings/iServer/trustRelationship',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(
    err_msg="Error deleting intelligence server - web server trust relationship."
)
def delete_iserver_web_trust(connection: Connection, error_msg=None):
    """Delete a trust relationship between the Web Server and the Intelligence
    Server. You obtain the authorization token needed to execute the request
    using POST /auth/login; you pass the authorization token in the request
    header.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.delete(
        endpoint='/api/admin/restServerSettings/iServer/trustRelationship',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(err_msg="Error testing intelligence server connection.")
def test_iserver_connection(connection: Connection, error_msg=None):
    """Test the connection between the Intelligence Server and the REST Server.
    Currently, only socket connectivity is tested. In the body parameter of the
    request, you specify the port and hostname of the Intelligence Server.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.post(
        endpoint='/api/admin/restServerSettings/iServer/connectionTest',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(err_msg="Error getting security settings.")
def get_security_settings(connection: Connection, error_msg=None):
    """Get relevant information about security settings, such as whether the
    secret key used for signing the identity token was set in the configuration
    file. If it was not set properly, an exception will be triggered.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/admin/restServerSettings/security',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(err_msg="Error updating security settings.")
def update_security_settings(connection: Connection, body, error_msg=None):
    """Update the security settings. In the body of the request you can specify
    the secret key that will be used in identity token generation, whether to
    enable Cross Origin Resource Sharing (CORS), and whether to disable URL
    validation when specifying domains for CORS configuration.

    Args:
        connection: Strategy One REST API connection object
        body: JSON-formatted definition of the dataset. Generated by
            `utils.formjson()`.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/security',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


# endregion

# region isrv settings


@ErrorHandler(err_msg="Error fetching I-Server settings.")
def get_iserver_settings_config(connection: Connection, error_msg=None):
    """For each setting, we provide different basic information to help client
    to render the settings.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/v2/iserver/settings/config',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error fetching I-Server settings.")
def get_iserver_settings(connection: Connection, error_msg=None):
    """This resource will retire resource 'GET iserver/settings' in the future
    version. Current version just cover Governing rule settings.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/v2/iserver/settings',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error updating I-Server settings.")
def create_iserver_settings(
    connection: Connection, body, error_msg=None, whitelist=('ERR001', 400)
):
    """Create some IServer governing settings.

    Example:
        body = {
            "maxUsedVirtualByte": {
                "value": 100
            },
            "workSetSwapPath": {
                "value": ".\\TmpPool"
            },
            "ignoreGovernorOnChild": {
                "value": true
            }
        }
    """
    return connection.put(
        endpoint='/api/v2/iserver/settings',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error updating I-Server settings.")
def update_iserver_settings(
    connection: Connection, body, error_msg=None, whitelist=('ERR001', 400)
):
    """Update some IServer governing settings.

    Example:
        body = {
            "maxUsedVirtualByte": {
                "value": 100
            },
            "workSetSwapPath": {
                "value": ".\\TmpPool"
            },
            "ignoreGovernorOnChild": {
                "value": true
            }
        }
    """
    return connection.patch(
        endpoint='/api/v2/iserver/settings',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error getting I-Server node {node} settings.")
def get_iserver_node_settings(connection: Connection, node, error_msg=None):
    """Get Intelligence Server configuration settings for a given server node
    within a cluster.

    Args:
        connection: Strategy One REST API connection object
        node: Intelligence Server host name
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint=f'/api/admin/restServerSettings/iServer/{node}',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(err_msg="Error updating Intelligence Server configuration settings.")
def update_iserver_configuration_settings(connection: Connection, body, error_msg=None):
    """Update Intelligence Server configuration settings.

    Args:
        connection: Strategy One REST API connection object
        body: object with settings to set
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/admin/restServerSettings/iServer',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error updating I-Server node {node} settings.")
def update_iserver_node_settings(connection: Connection, body, node, error_msg=None):
    """Update Intelligence Server configuration settings for a given server
    node within a cluster.

    Args:
        connection: Strategy One REST API connection object
        node: Intelligence Server host name
        error_msg (string, optional): Custom Error Message for Error Handling
        body:{"loadBalanceFactor": int,
              "initialPoolSize": int,
              "maxPoolSize": int}

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint=f'/api/admin/restServerSettings/iServer/{node}',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
        json=body,
    )


@ErrorHandler(err_msg="Error deleting I-Server node {node} settings.")
def delete_iserver_node_settings(connection: Connection, node, error_msg=None):
    """Removes Intelligence Server configuration settings for a given server
    node within a cluster. This can be useful to clear out settings so that a
    default value is applied.

    Args:
        connection: Strategy One REST API connection object
        node: Intelligence Server host name
        error_msg (string, optional): Custom Error Message for Error Handling
    """
    return connection.delete(
        endpoint=f'/api/admin/restServerSettings/iServer/{node}',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


# endregion

# region storage svc


@ErrorHandler(err_msg="Error getting Library storage configuration.")
def storage_service_get_configs(
    connection: Connection,
    fields: str | None = None,
    error_msg: str | None = None,
):
    """Get the storage type, location, and cloud storage configurations.

    Args:
        connection (Connection): Strategy One REST API connection object
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object. 200 on success.
    """
    return connection.get(
        endpoint='/api/mstrServices/library/storage', params={'fields': fields}
    )


@ErrorHandler(err_msg="Error validating Library storage configuration.")
def storage_service_validate_configs(
    connection: Connection, body: dict, error_msg: str | None = None
):
    """Validate the storage type, location, and cloud storage configurations.
    Following privilege: DssXmlPrivilegesAdministerEnvironment is required to
    invoke this endpoint.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): {
            "sharedFileStore": {
                "type": str
                    ("unset", "unknown", "file_system", "S3", "Azure", "GCS"),
                "alias": str (optional),
                "location": str (optional),
                "s3Region": str (optional),
                "awsAccessId": str (optional),
                "awsSecretKey": str (optional),
                "azureStorageAccountName": str (optional),
                "azureSecretKey": str (optional),
                "gcsServiceAccountKey": str (optional)
            }
        }
            "sharedFileStore"/"type" supports:
            "file_system", "S3", "Azure", "GCS"
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object. 204 on success.
    """
    return connection.post(
        endpoint='/api/mstrServices/library/storage/validation',
        json=body,
    )


@ErrorHandler(err_msg="Error updating Library storage configuration.")
def storage_service_update_configs(
    connection: Connection, body: dict, error_msg: str | None = None
):
    """Update the storage type, location, and cloud storage configurations.
    Following privilege: DssXmlPrivilegesAdministerEnvironment is required to
    invoke this endpoint.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): {
            "sharedFileStore": {
                "type": str
                    ("unset", "unknown", "file_system", "S3", "Azure", "GCS"),
                "alias": str (optional),
                "location": str (optional),
                "s3Region": str (optional),
                "awsAccessId": str (optional),
                "awsSecretKey": str (optional),
                "azureStorageAccountName": str (optional),
                "azureSecretKey": str (optional),
                "gcsServiceAccountKey": str (optional)
            }
        }
            "sharedFileStore"/"type" supports:
            "file_system", "S3", "Azure", "GCS"
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object. 204 on success.
    """
    return connection.patch(
        endpoint='/api/mstrServices/library/storage',
        json=body,
    )


# endregion

# region fences


@ErrorHandler(err_msg="Error getting fences list.")
def list_fences(
    connection: Connection, fields: str | None = None, error_msg: str | None = None
) -> Response:
    """Get the list of fences.

    Args:
        connection (Connection): Strategy One REST API connection object
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(endpoint='/api/v2/iserver/fences', params={'fields': fields})


@ErrorHandler(err_msg="Error creating a new fence.")
def create_fence(
    connection: Connection,
    body: dict,
    fields: str | None = None,
    error_msg: str | None = None,
) -> Response:
    """Create a new fence.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): Fence creation data
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.

    """
    return connection.post(
        endpoint='/api/v2/iserver/fences',
        params={'fields': fields},
        json=body,
    )


@ErrorHandler(err_msg="Error getting fence with ID: {id}")
def get_fence(
    connection: Connection,
    id: str,
    fields: str | None = None,
    error_msg: str | None = None,
) -> Response:
    """Get a fence by ID.

    Args:
        connection (Connection): Strategy One REST API connection object
        id (str): Fence ID
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint=f'/api/v2/iserver/fences/{id}',
        params={'fields': fields},
    )


@ErrorHandler(err_msg="Error deleting fence with ID: {id}")
def delete_fence(
    connection: Connection,
    id: str,
    error_msg: str | None = None,
    journal_comment: str | None = None,
) -> Response:
    """Delete a fence by ID.

    Args:
        connection (Connection): Strategy One REST API connection object
        id (str): Fence ID
        error_msg (str, optional): Custom Error Message for Error Handling
        journal_comment (str, optional): Comment that will be added to the
            object's change journal entry.

    Returns:
        Complete HTTP response object.
    """
    params = add_comment_to_dict(None, journal_comment)
    return connection.delete(endpoint=f'/api/v2/iserver/fences/{id}', params=params)


@ErrorHandler(err_msg="Error updating fence with ID: {id}")
def update_fence(
    connection: Connection,
    id: str,
    body: dict,
    fields: str | None = None,
    error_msg: str | None = None,
) -> Response:
    """Update a fence by ID.

    Args:
        connection (Connection): Strategy One REST API connection object
        id (str): Fence ID
        body (dict): Fence update data
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.patch(
        endpoint=f'/api/v2/iserver/fences/{id}',
        params={'fields': fields},
        json=body,
    )


# endregion

# region clusters


@ErrorHandler(err_msg="Error getting cluster startup membership information.")
def get_cluster_startup_membership(
    connection: Connection, fields: str | None = None, error_msg: str | None = None
) -> Response:
    """Get the cluster startup membership information.

    Args:
        connection (Connection): Strategy One REST API connection object
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/iserver/clusterStartupMembership',
        params={'fields': fields},
    )


@ErrorHandler(err_msg="Error updating cluster startup membership information.")
def update_cluster_startup_membership(
    connection: Connection,
    body: dict,
    fields: str | None = None,
    error_msg: str | None = None,
) -> Response:
    """Update the cluster startup membership information.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): Cluster startup membership update data
        fields (str, optional): A comma-separated list of fields to include
                in the response. By default, all fields are returned.
        error_msg (str, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.put(
        endpoint='/api/iserver/clusterStartupMembership',
        json=body,
        params={'fields': fields},
    )


@ErrorHandler(err_msg="Error getting cluster membership information.")
def get_cluster_membership_admin(connection: Connection, error_msg=None):
    """Get IServer cluster membership information via legacy API.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/admin/iServer/clusterMembership',
        headers={
            'X-MSTR-ProjectID': None,
            # TODO: this method requires rework (CGPY-3568)
            'Authorization': connection._get_authorization(),
        },
    )


@ErrorHandler(err_msg="Error getting cluster membership information.")
def get_cluster_membership(connection: Connection, error_msg=None):
    """Get IServer cluster membership information.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """
    return connection.get(
        endpoint='/api/monitors/iServer/clusterMembership',
        headers={'X-MSTR-ProjectID': None},
    )


# endregion

# region telemetry


@ErrorHandler(err_msg="Error getting Telemetry Configuration.")
def OLD_get_telemetry_configuration(  # NOSONAR
    connection: Connection,
    project_id: str | None = None,
    is_live: bool = False,
) -> Response:
    """Get Telemetry Configuration.

    The configuration indicates if the client telemetry and basic statistics
    are enabled for each project (or a selected one if `project_id` is provided
    or `connection` has it selected).

    Args:
        connection (Connection): Strategy One REST API connection object.
        project_id (str, optional): Project ID to get the telemetry settings
            for. If not provided, the project ID from the connection will be
            used.
        is_live (bool, optional): Whether to get live settings and refresh
            cache. Default is False (get cached info).

    Returns:
        Complete HTTP response object.
    """

    project_id = project_id or connection.project_id
    params = {}
    headers = None

    if project_id:
        params['projectId'] = project_id
        headers = {'X-MSTR-ProjectID': project_id}

    if is_live:
        params['isLive'] = is_live

    return connection.get(
        endpoint='/api/mstrServices/library/telemetryProducer/settings',
        headers=headers,
        params=params,
    )


@ErrorHandler(err_msg="Error getting Telemetry Configuration.")
def get_telemetry_configuration(
    connection: Connection,
) -> Response:
    """Get Telemetry Configuration for all projects (whole environment).

    Args:
        connection (Connection): Strategy One REST API connection object.

    Returns:
        Complete HTTP response object.
    """

    return connection.get(
        endpoint='/api/iserver/telemetryProducer',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error getting Telemetry Configuration for project {project_id}.")
def get_telemetry_configuration_for_project(
    connection: Connection,
    project_id: str,
) -> Response:
    """Get Telemetry Configuration for a project.

    Args:
        connection (Connection): Strategy One REST API connection object.
        project_id (str): Project ID to get the telemetry settings for.

    Returns:
        Complete HTTP response object.
    """

    return connection.get(
        endpoint=f'/api/iserver/telemetryProducer/{project_id}',
        headers={'X-MSTR-ProjectID': project_id},
    )


@ErrorHandler(err_msg="Error updating Telemetry Basic Configuration.")
def update_telemetry_basic_configuration(
    connection: Connection,
    body: dict,
) -> Response:
    """Update Telemetry Basic Configuration for all projects.

    Note:
        It applies only to "basic stats" and "client telemetry" properties.

    Args:
        connection (Connection): Strategy One REST API connection object.
        body (dict): Telemetry configuration update data.

    Returns:
        Complete HTTP response object.
    """

    return connection.put(
        endpoint='/api/mstrServices/library/telemetryProducer/settings',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(
    err_msg="Error updating Telemetry Configuration for project {project_id}."
)
def update_telemetry_configuration_for_project(
    connection: Connection,
    project_id: str,
    body: dict,
) -> Response:
    """Update Telemetry Configuration for a project.

    Args:
        connection (Connection): Strategy One REST API connection object
        project_id (str): Project ID to update the telemetry settings for.
        body (dict): Telemetry configuration update data.

    Returns:
        Complete HTTP response object.
    """

    return connection.patch(
        endpoint=f'/api/iserver/telemetryProducer/{project_id}',
        headers={'X-MSTR-ProjectID': project_id},
        json=body,
    )


@ErrorHandler(err_msg="Error getting Telemetry Connections Info.")
def get_telemetry_connections_info(connection: Connection) -> Response:
    """Get the telemetry server connections from Library and I-Server.
    If the connection in Library is the default localhost:9092, overwrites it
    with the connection in I-Server.

    Note:
        Keys returned in response dict are:
        ```
        'kafkaProperties.bootstrap.servers': '127.0.0.1:9092,...',
        'kafkaProperties.security.protocol': 'PLAINTEXT',
        'iserver.bootstrap.servers': '127.0.0.1:9092,...',
        ```
        Multiple values in `.servers` keys are still a string but values are
        separated by comma.

    Args:
        connection (Connection): Strategy One REST API connection object

    Returns:
        Complete HTTP response object.
    """

    return connection.get(
        endpoint='/api/mstrServices/telemetryServer/settings',
        headers={'X-MSTR-ProjectID': None},
    )


@ErrorHandler(err_msg="Error updating Telemetry Connections Info.")
def update_telemetry_connections_info(
    connection: Connection,
    body: dict,
) -> Response:
    """Update the telemetry server connections in both Library and I-Server.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): Telemetry connections update data

    Returns:
        Complete HTTP response object.
    """

    return connection.put(
        endpoint='/api/mstrServices/telemetryServer/settings',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


@ErrorHandler(err_msg="Error testing Telemetry Connections.")
def validate_telemetry_connections(
    connection: Connection,
    body: dict,
) -> Response:
    """Verify connection between Library Server and Telemetry Server.

    Check the exception in each node for the detailed failure message.

    Note:
        Use `get_telemetry_connections_info` to get data (`body`) to test.

    Args:
        connection (Connection): Strategy One REST API connection object
        body (dict): Telemetry connections test data

    Returns:
        Complete HTTP response object.
    """

    return connection.post(
        endpoint='/api/mstrServices/telemetryServer/connectionTest',
        headers={'X-MSTR-ProjectID': None},
        json=body,
    )


# endregion

# region cfg lock


@ErrorHandler(err_msg="Error getting configuration lock information.")
def get_configuration_lock(connection: Connection, error_msg=None) -> Response:
    """Query the lock information of the configuration of the environment.

    Args:
        connection: Strategy One REST API connection object
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object.
    """

    return connection.get(endpoint='/api/iserver/lock')


@ErrorHandler(err_msg="Error updating configuration lock.")
def update_configuration_lock(
    connection: Connection, body: dict, error_msg=None
) -> Response:
    """Update the lock information of the configuration of the environment.

    Args:
        connection: Strategy One REST API connection object
        body (dict): Configuration lock update data
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object. 204 on success.
    """

    return connection.put(endpoint='/api/iserver/lock', json=body)


@ErrorHandler(err_msg="Error deleting configuration lock.")
def delete_configuration_lock(
    connection: Connection,
    lock_type: str,
    force: bool | None = None,
    lock_id: str | None = None,
    error_msg=None,
) -> Response:
    """Unlock the configuration of the environment.

    Args:
        connection: Strategy One REST API connection object
        lock_type (str): Type of the lock to unlock
        force (bool, optional): Whether to force unlock the lock
        lock_id (str, optional): ID of the lock
        error_msg (string, optional): Custom Error Message for Error Handling

    Returns:
        Complete HTTP response object. 204 on success.
    """

    return connection.delete(
        endpoint='/api/iserver/lock',
        params={'lockType': lock_type, 'force': force, 'lockId': lock_id},
    )


# endregion
